dbString: postgres://user:password@host:port/dbname
dbLogMode: 3
debug: true
gcpProjectID: marincor
storageBucket: bucketStorage
storageBaseFolder: assets
mailgunKey:
mailgunDomain:
emailSenderAddress:
emailSenderLabel:
environment: local